<?php
    return array(
         'yousu'=>array('name'=>'优速快递模板格式',
		                          'fields'=>array(
		                                               array('title'=>'序号','name'=>'id'), 
		                                               array('title'=>'用户QQ','name'=>'user_id'), 
		                                               array('title'=>'快递单号','name'=>'note_no'),
		                                               array('title'=>'发货省份+发货电话','name'=>"concat(send_province,',',send_shouji)"),//（广东省广州市天河区）
		                                               array('title'=>'收货详细地址','name'=>"concat(rec_name,'，',rec_shouji,'，',rec_phone,'，',rec_address,'，',rec_zipcode)")
		                                                )  
								  ),
		'nengda'=>array('name'=>'能达快递模板格式',
		                            'fields'=>array(
		                            						array('title'=>'序号','name'=>'id'), 
		                                               		array('title'=>'用户QQ','name'=>'user_id'), 
		                                                     array('title'=>'快递单号','name'=>'note_no'),
		                                                     array('title'=>'发货省','name'=>'send_province'),
		                                                     array('title'=>'发货市','name'=>'send_city'),
		                                                     array('title'=>'发货人','name'=>'send_name'),
		                                                     array('title'=>'收货市','name'=>'rec_city'),
		                                                     array('title'=>'收货人','name'=>'rec_name'),
		                                                     array('title'=>'收货地址','name'=>'rec_address'), 
									                  )
									),
	 'quanfeng'=>array('name'=>'全国互发全峰客户使用',
			                               'fields'=>array(
			                               				  array('title'=>'序号','name'=>'id'), 
		                                              	  array('title'=>'用户QQ','name'=>'user_id'), 
			                             				  array('title'=>'快递单号','name'=>'note_no'), 
			                             				  array('title'=>'寄件省份','name'=>'send_province'),
			                             				  array('title'=>'寄件市','name'=>"send_city"),
			                             				  array('title'=>'发货人-手机','name'=>"concat(send_name,'.',send_shouji)"),
			                             				  array('title'=>'收件省份','name'=>'rec_province'),
			                             				  array('title'=>'收件市','name'=>"rec_city"),
			                             				  array('title'=>'签收人','name'=>"rec_name"),
			                             				  array('title'=>'收件详细地址','name'=>"concat(rec_name,'，',rec_shouji,'，',rec_phone,'，',rec_address,'，',rec_zipcode)"),
										                     )
			                    ),
		'longbang'=>array('name'=>'龙邦速递模板格式',
		                            'fields'=>array(
		                            						 array('title'=>'序号','name'=>'id'), 
		                                               		 array('title'=>'用户QQ','name'=>'user_id'), 
		                                                     array('title'=>'快递单号','name'=>'note_no'),
		                                                     array('title'=>'发货省','name'=>'send_province'),
		                                                     array('title'=>'发货市区','name'=>'concat(send_city,send_district)'),
		                                                     array('title'=>'发货人','name'=>'send_name'),
		                                                     array('title'=>'收货地址','name'=>'rec_address'),
		                                                     array('title'=>'收货人','name'=>'rec_name'),
		                                                     array('title'=>'收货电话','name'=>'rec_shouji'), 
									                  )
									),		
		'chengshi100'=>array('name'=>'城市100模板格式',
		                            'fields'=>array(
		                           							 array('title'=>'序号','name'=>'id'), 
		                                              		 array('title'=>'用户QQ','name'=>'user_id'), 
		                                                     array('title'=>'快递单号','name'=>'note_no'),
		                                                     array('title'=>'发货省','name'=>'send_province'),
		                                                     array('title'=>'发货市','name'=>'send_city'),
		                                                     array('title'=>'收货市','name'=>'rec_city'), 
		                                                     array('title'=>'收货人','name'=>'rec_name'),
		                                                     array('title'=>'收货地址','name'=>'rec_address'), 
									                  )
									),										                    
		 );
?>